name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i -g npm@latest

      - run: npm i -ws
      - run: npm run lint -ws
      - run: npm run build -ws
      - run: npm pack -ws
      - name: Upload
        uses: actions/download-artifact@v4
        with:
          name: package
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: "@ythrinathareddy"
      - run: echo "registry=https://npm.pkg.github.com/@ythrinathareddy" >> .npmrc
      - run: npm publish package.zip
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITUSER_TOKEN}}
